### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by colinlienard** [colinlienard/gitlight#129]
- [ ] Don't show again doesn't work when page reloaded
- [x] Add a setting to show or not notifications sync timer
- [x] Cursor grab on notifications
- [x] Better looking buttons
- [x] Close modals on window blur
- [ ] Better animation when hiding sidebar
- [x] Do not click on links when dragging notifications
- [x] Fix text in checkboxes and notifications being cut
- [x] Add number of done notifications in the done button

**Comment by jimit-exe** [comment]
I have implemented the setting to show or not notifications sync timer.
