### ISSUE TITLE
Add GitHub Enterprise Integration

### ISSUE THREAD

**Issue by Tragio** [colinlienard/gitlight#132]
Thank you for your amazing work! 🚀

What do you think about GitHub Enterprise integration? 😁

**Comment by colinlienard** [comment]
I actually don't know much about GitHub Enterprise but if an admin can authorise GitLight to use the notification API and if you can create a fine-grained personal access token, everything should work fine

You can check organization access [here](https://github.com/settings/connections/applications/3db3813c5828d8bbe530)
and for fine-grained personal access tokens, everything is explained in the app, under Settings > Permissions

Let me know if you encounter any problems, and thanks for the kind words!
