### ISSUE TITLE
[feat] Support for ARM processors (Apple Silicon - M1, Windows ARM, Linux ARM)

### ISSUE THREAD

**Issue by Bellisario** [colinlienard/gitlight#143]
Currently there are no releases for ARM processors.

For example, I'm on a M2 Mac Mini and there is no release for Apple Silicon (and I could only use the x64 version via Rosetta 2).

**Comment by Bellisario** [comment]
Update: I found this closed issue (not sure why didn't show up while searching): #84 

Looking into the comments, seems developers were waiting a pull merge from Tauri, and now it seems to be merged: https://github.com/tauri-apps/tauri-action/pull/301

**Comment by colinlienard** [comment]
I had already tried to build the app for arm64 but I felt the way I was doing it wasn't clean, and also the built app from the CI was "damaged" and I wasn't sure what that meant

But it sure would be nice to do that, I'll try to look into it again.
