### ISSUE TITLE
[Feature request] Support for multiple Github accounts

### ISSUE THREAD

**Issue by Himujjal** [colinlienard/gitlight#147]
Is it a possibility to add multiple Github accounts and to be able to switch accounts?

**Comment by colinlienard** [comment]
It is not possible right now and I don't think it's a feature that would be worth implementing, at least before the GitLab integration, sorry 🥲

For now what you can do is use the desktop app with an account and the web app with another account, but you won't have push notifications

**Comment by Himujjal** [comment]
Thanks for the prompt reply
