### ISSUE TITLE
GitHub auth broken

### ISSUE THREAD

**Issue by dgrebb** [colinlienard/gitlight#161]
Tried a few things...

- use in browser
- app on desktop
- unblock all privacy extensions/fresh browser with extensions disabled

In-browser auth returns:

`https://gitlight.app/auth/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=08f7475f4b3c16730699e52cae129be0`

Desktop app:

`https://gitlight.app/auth/login?from_app=true`

![image](https://github.com/colinlienard/gitlight/assets/445891/21ee2050-3895-4b37-8a8b-70597671c3c0)

---

Excited to try this out! Curious to see a Svelte desktop app in action :)

**Comment by colinlienard** [comment]
Well dumb me forgot to update the github app redirect url...
Should be fine now

Thanks for pointing this out!

**Comment by dgrebb** [comment]
Possibly need a new desktop build as well? Web app now working, but desktop stuck at login:

![2023-08-12 10 44 22](https://github.com/colinlienard/gitlight/assets/445891/341a285e-f9bd-4d42-9ddf-12ecc3f157a4)

Cheers and thanks for being so quick to respond. Looking forward to how things develop :)

**Comment by colinlienard** [comment]
New build will be available in about 15min, should be good for real this time 😅
