### ISSUE TITLE
Tray-app mode

### ISSUE THREAD

**Issue by colinlienard** [colinlienard/gitlight#180]
https://betterprogramming.pub/create-menubar-app-with-tauri-510ab7f7c43d
https://docs.rs/tauri/1.4.1/tauri/window/struct.Window.html

Back:
  - Positioned under the tray icon
  - Open and close when clicking on it
  - Cannot move window or use the window's controls (https://github.com/tauri-apps/tauri/pull/6665/commits/4e0acca02b94880295fd7a6b2d22bbd745b1a468)
  - Not in the dock (https://github.com/tauri-apps/tauri/discussions/6093)

Front:
  - No header
  - No done button
  - List mode
  - Way to toggle between normal and tray mode

**Comment by siegenthalerroger** [comment]
@colinlienard it appears that the subtask "Not in the dock" wasn't completed in this. Should I open an issue for this?
