### ISSUE TITLE
Toggling the sidebar in browser app causes unintended interaction

### ISSUE THREAD

**Issue by Fang095** [colinlienard/gitlight#198]
When toggling the Sidebar in the browser app`Ctrl + s` triggers the page to save on Windows and similarly `Cmd + s` causes the same interaction on MacOS.

I would suggest maybe changing it to trigger on the `b` key press similar to VSCode.

**Comment by colinlienard** [comment]
It maybe be possible to prevent default this behaviour

Thanks for your feedback!
