### ISSUE TITLE
Add option to turn off the menubar notification count in mac os 

### ISSUE THREAD

**Issue by mcrascal** [colinlienard/gitlight#202]
Love the project, thank you for building this! 

I'd like to be able to just use the app, not the item in the menubar if possible.

**Comment by colinlienard** [comment]
Thanks for your feedback!
Sure, I'll add an option to disable it

**Comment by colinlienard** [comment]
@mcrascal Hi, I added the option in the settings, I will publish a new release soon with this changes

<img width="463" alt="Screenshot 2023-10-06 at 21 12 47" src="https://github.com/colinlienard/gitlight/assets/64312634/242b377a-1140-420a-898a-d4f87cf5f241">
