### ISSUE TITLE
logged in but can not load data

### ISSUE THREAD

**Issue by LKHcoding** [colinlienard/gitlight#203]
I logged in with GitHub.
I put PAT in gitLight right way.

>  I checked
> - notification settings
> - PAT permissions(access to all repositories)

<br />
  
However, gitLight does not load data.
(repositories, pull requests, issues ... etc.)

![image](https://github.com/colinlienard/gitlight/assets/55027765/7ccbaa8d-6c14-4a81-895c-1462076b09e9)
It looks like the token has not been used.

<br />
  

Please let me know what the problem is

Thanks.

![image](https://github.com/colinlienard/gitlight/assets/55027765/ea533e0e-f922-42a6-a565-82aa16c28a5e)

**Comment by LKHcoding** [comment]
> If you want to have notifications from private repositories, the GitHub organization that owns them must grant GitLight access to notifications, is that the case? You can check this here: https://github.com/settings/connections/applications/3db3813c5828d8bbe530

@colinlienard 

i added two PAT.

added resource owner
- personal(my) id
- specific organization

but not working both
i already granted
![image](https://github.com/colinlienard/gitlight/assets/55027765/51bd3759-5d29-4553-803a-583ccbce068d)

**Comment by colinlienard** [comment]
Are you the only user in your organization? If you don't have any other person/bot doing activity, you won't receive any notifications.

You can go to [GitHub notifications](https://github.com/notifications) and check for notifications. If you don't have any, you won't get any in GitLight either.

**Comment by LKHcoding** [comment]
> Are you the only user in your organization? If you don't have any other person/bot doing activity, you won't receive any notifications.
> 
> You can go to [GitHub notifications](https://github.com/notifications) and check for notifications. If you don't have any, you won't get any in GitLight either.

I can get a comment notification on this issue.
I wanted to test it in a repository that I use alone, but I didn't know it was impossible.
thanks!
