### ISSUE TITLE
Open menu bar window anywhere

### ISSUE THREAD

**Issue by anubra266** [colinlienard/gitlight#216]
When I open the menu bar on mac, it always switches to desktop

https://github.com/colinlienard/gitlight/assets/30869823/4512678e-01d6-4c15-b6c9-fcb24d848fc7

**Comment by colinlienard** [comment]
Thanks for your feedback!
Unfortunately this is not fixable right now with Tauri, I tried multiple things but none of them worked
It might be possible in the v2 though

Btw this behaviour also occurs with other apps when you're in fullscreen, Asana for example
