### ISSUE TITLE
Cannot login to GitLab

### ISSUE THREAD

**Issue by christoff-linde** [colinlienard/gitlight#218]
When trying to login to GitLab, I keep getting a error (on GitLab) stating that the _The redirect URI included is not valid._

This is happening both from the Desktop app and the Web client. Have also tried disabling any form of adblocker, but had no effect.

**Browser:** Arc Browser Version 1.14.0 (42789)
Chromium Engine Version 118.0.5993.117
**OS:** macOS 14.0 (23A344)

### For Reference
![image](https://github.com/colinlienard/gitlight/assets/38110658/2c0f74fc-3f43-404e-a0e9-a75718a28310)

**Comment by colinlienard** [comment]
Thanks for reporting this!
This should be fixed now @christoff-linde 
I will also publish a new release today with some other bugfixes

**Comment by christoff-linde** [comment]
Awesome! 

This is a really cool app, excited to see where it goes :)

**Comment by colinlienard** [comment]
Thanks for the kind words!
(Coming soon: new design, new logo and light mode)
