### ISSUE TITLE
Repo cannot be added from contributed project

### ISSUE THREAD

**Issue by nightbikerdev** [colinlienard/gitlight#220]
When trying to add a repo `https://gitlab.com/<COMPANY_NAME>/projects/<GROUP_NAME>/<REPO_NAME>` I get an error  `Invalid URL`. The access role for this project is 'Maintainer'.

**Comment by colinlienard** [comment]
I think you can simply do `https://gitlab.com/<GROUP_NAME>/<REPO_NAME>`, or just go on the page of the project, copy the url and paste it in the app. Beware, the project path can be different from the actual name as written [here](https://docs.gitlab.com/ee/api/rest/index.html#namespaced-path-encoding). Maybe I should add a clarification about that somewhere

For example, I created a group called `group-test` and a project inside it called `project-test`. The url of the project is https://gitlab.com/group-test5943045/project-test

Does this help @nightbikerdev?

**Comment by christoff-linde** [comment]
> When trying to add a repo `https://gitlab.com/<COMPANY_NAME>/projects/<GROUP_NAME>/<REPO_NAME>` I get an error `Invalid URL`. The access role for this project is 'Maintainer'.

I have this issue as well when trying to add a repo specifically for work (i.e. something like `https://gitlab.com/<COMPANY_NAME>/projects/<GROUP_NAME>/<REPO_NAME>`). 

Could it be because the repo is owned by a company and not a personal account causing some form of permissions issue?

**Comment by nightbikerdev** [comment]
@colinlienard Unfortunately, it did not help. I think @christoff-linde is right. It seems gitlab does not have a good way to get repositories where user contributed.

**Comment by colinlienard** [comment]
I may have an idea, I'll test tonight and maybe I'll ask you to test things too if you agree, because I don't have access to private company repositories on GitLab

**Comment by colinlienard** [comment]
@nightbikerdev @christoff-linde Could you please test again on the website? Not on the app, I didn't make a new release

If it still doesn't work, could you go to https://gitlight.app/gitlab-test and take a screenshot of what you see?

Could you also test the repositories with:
- `https://gitlab.com/<GROUP_NAME>/<REPO_NAME>`
- `https://gitlab.com/<COMPANY_NAME>/<GROUP_NAME>/<REPO_NAME>`

**Comment by christoff-linde** [comment]
So can confirm that for me it does work with `https://gitlab.com/<GROUP_NAME>/<SUB_GROUP_NAME>/<SUB_GROUP_NAME>/<REPO_NAME>` (as well as slight variations of this).

**Comment by christoff-linde** [comment]
I would be kinda cool to have the option to have the repos be added in "bulk" by for e.g., specifying just `https://gitlab.com/<GROUP_NAME>/<SUB_GROUP_NAME>`, if that is even technically possible. Would especially be useful if one has a lot of repos to keep track of

**Comment by nightbikerdev** [comment]
Now It works for my case :+1:

**Comment by colinlienard** [comment]
Nice! Thanks to both of you for helping on this
I'll publish a fix soon followed by a new release

> I would be kinda cool to have the option to have the repos be added in "bulk" by for e.g., specifying just `https://gitlab.com/<GROUP_NAME>/<SUB_GROUP_NAME>`, if that is even technically possible. Would especially be useful if one has a lot of repos to keep track of

Good idea, I'll look into it
