### ISSUE TITLE
GitLab PR Markdown Content Rendering

### ISSUE THREAD

**Issue by christoff-linde** [colinlienard/gitlight#222]
### Description
In some cases, GitLab flavoured markdown comments are not rendering "properly" on GitLight notifications (see screenshots below). I am unsure wether the current behaviour is intended, thus this issue :) 

### For Reference
<img width="1303" alt="image" src="https://github.com/colinlienard/gitlight/assets/38110658/3cbc32a3-bc65-4b10-a670-63d7d179e14b">

_Preview in GitLight_

<img width="1034" alt="image" src="https://github.com/colinlienard/gitlight/assets/38110658/faa07c69-777b-410f-9b7a-56d491c17e9d">

_Actual GitLab flavoured markdown content in GitLab (as a comment on a PR)_

**Comment by colinlienard** [comment]
Thanks for reporting this!
You're right, I just forgot to parse markdown comments for gitlab notifications, I'll fix this
