### ISSUE TITLE
Add button/visual indicator for un-hiding navbar

### ISSUE THREAD

**Issue by christoff-linde** [colinlienard/gitlight#236]
### Description

_Preface: this might just be a personal problem, but keen to hear your opinion._

But, when hiding the sidebar, it took me quite a while to figure out that you can un-hide the sidebar by simply clicking on the GitLight logo.

Maybe the existing `<<` icon that is used for collapsing the sidebar can be used to un-hide it as well?

**Comment by colinlienard** [comment]
If it is unclear for you, it probably is also unclear for other people (or maybe everyone 😓), so I will make a change
Thanks!
