### ISSUE TITLE
App stuck in Syncing mode

### ISSUE THREAD

**Issue by rvasseur31** [colinlienard/gitlight#273]
Hi !

First of all thank you for creating this wonderful app.

Unfortunately, I can't use it to the full, but I can see a lot of good in it. Since I installed the app, when I launch the app everything goes fine, then a few minutes later, the app gets stuck in a synchronization mode and the app becomes unusable, I also get notifications that I've already seen and passed in done

Here is a video that showing my problem : 

https://github.com/colinlienard/gitlight/assets/46020438/f6adbbb8-1399-4614-85c6-d635d6805988

**Comment by colinlienard** [comment]
Hi, thanks for the kind words!

Could you please try to reproduce the issue in the browser and then send a screenshot of the console?

**Comment by rvasseur31** [comment]
Hi !

I didn't manage to reproduce the error, I'll close the issue. If it happens again, I'll try to recover the web error.

In the meantime, I've tried to build the app in dev to see if I could reproduce it, and since then, the error has disappeared.
