### ISSUE TITLE
Tray icon blank under Windows 11

### ISSUE THREAD

**Issue by cbouc** [colinlienard/gitlight#283]
As is [in]visible on this screenshot (circled in red).
![GitLightTrayIconBlankBug](https://github.com/colinlienard/gitlight/assets/5592982/cd5abcde-3238-468c-b959-4e29c5234d11)

**Comment by colinlienard** [comment]
Hey @cbouc just published a new release with the 2 fixes
Thanks for reporting theses problems!

**Comment by cbouc** [comment]
Thank you for the (fast!) fixes, I now see the icon in the tray and the dashboard is restored by the menu when it’s minimized!
