### ISSUE TITLE
Feature Request: Link to Commit/MR from Notifications

### ISSUE THREAD

**Issue by fixcik** [colinlienard/gitlight#308]
Hello,

Thank you for the excellent application! It has greatly improved my workflow.

I would like to suggest a small but impactful improvement: it would be very useful to have the ability to navigate directly to a commit or Merge Request (MR) when clicking on a notification. This would enhance the user experience by making it easier to review changes associated with specific notifications.

Thank you for considering this enhancement!

Best regards, fixcik

**Comment by colinlienard** [comment]
Thank you for the kind words!
Unfortunately, it doesn't seem possible to achieve this with Tauri at the moment: https://github.com/tauri-apps/plugins-workspace/issues/2150
If it becomes feasible in the future, I would definitely add this feature.
