### ISSUE TITLE
Infinite loading with error `Uncaught (in promise) Error: Invalid notification type: WorkflowRun`

### ISSUE THREAD

**Issue by JReinhold** [colinlienard/gitlight#66]
After authenticating with GitHub, all I get is infinite loading of notifications. In the console, I can see the following error:

```
caught (in promise) Error: Invalid notification type: WorkflowRun
    at hl (3.b6bc30a9.js:1:15748)
    at 3.b6bc30a9.js:20:11772
    at Array.map (<anonymous>)
    at a (3.b6bc30a9.js:20:11761)
hl @ 3.b6bc30a9.js:1
(anonymous) @ 3.b6bc30a9.js:20
a @ 3.b6bc30a9.js:20
await in a (async)
(anonymous) @ 3.b6bc30a9.js:20
```

I guess I have some notifications which are of a type that you don't yet support?

Let me know if you need further info.

![image](https://github.com/colinlienard/gitlight/assets/5678122/d309ea54-4736-4e11-a1aa-2a021112e7ff)

**Comment by colinlienard** [comment]
Thanks for creating this issue!
Interestingly, I never ran into this type of notification but I know how to fix the error
(Might have to add error handling at some point 😅)

**Comment by katsuki-yuri** [comment]
the same issue with 0.3.0 installed client app on MacOS
![Screenshot 2023-05-31 at 15 33 38](https://github.com/colinlienard/gitlight/assets/54666588/8eb3a96b-bc12-438a-bd19-3a7c53c144a3)

**Comment by katsuki-yuri** [comment]
However, traybar is working perfectly!
![Screenshot 2023-05-31 at 15 34 48](https://github.com/colinlienard/gitlight/assets/54666588/c307f19e-e306-4e6f-a7e1-0324fbb1760d)

**Comment by Nyalab** [comment]
yes, same problem of infinite loading with a clean install here
