### ISSUE TITLE
Feature Request: More advanced filtering

### ISSUE THREAD

**Issue by anthonyshew** [colinlienard/gitlight#68]
I'd love to be able to get even more granular with my filtering.

A few use cases that I've ran into pretty quickly:
- Only show me open PRs (hide ones that are closed)
- Only show commits from a certain person(s)
- Only show PRs from a certain person(s)
- Only show issues from a certain person(s)

**Comment by colinlienard** [comment]
This will definitely happen, just need to think a bit about the design
