### ISSUE TITLE
Bug: Pull request showing as open but I merged it

### ISSUE THREAD

**Issue by anthonyshew** [colinlienard/gitlight#69]
To get into this state, I went through these steps:
1. Opened GitLight
2. Clicked on the PR
3. Merged it on GitHub
4. Went back to GitLight
5. After a few refreshes, GitLight is still showing the PR as open

PR: https://github.com/vercel/turbo/pull/5134
<img width="443" alt="CleanShot 2023-05-31 at 04 19 05@2x" src="https://github.com/colinlienard/gitlight/assets/35677084/7bfccec3-a1e5-4681-83da-15aa4e1f6268">

**Comment by colinlienard** [comment]
Might have found why this happen... Stay tuned!
