### ISSUE TITLE
Feature Requests: Heuristics for expressing priority

### ISSUE THREAD

**Issue by anthonyshew** [colinlienard/gitlight#70]
Working with open source at scale, it can be difficult to assess priority in the GitHub UI. We have to work through various levels of  labels, reactions, and other filtering in the UI.

These things can be bookmarked and the pain can be eased - but its still difficult and consumes a lot of time when its something you are working with every day. If GitLight were able to smartly prioritize issues, pull requests, and discussions to surface them sooner, we could work much faster.

In terms of the heuristics that could be used, I can think of (I'll use arrows to express bumping priority up and down):
- ⬆️ I'm assigned to the issue/PR.
- ⬆️ How many comments has this issue/PR gotten?
- ⬆️ How many reactions have been seen on this issue/PR?
- ⬇️ If an issue needs a reproduction, we can bump down the priority since we are waiting on more inputs.

There could also be a layer of tunable heuristics:
- Assign a numerical value to a label (Maybe I want to prioritize bugs so I give that label a big number)
-  If I want to give more weight to PRs over issues, I can tune PRs to be higher.

Altogether, this would be a really great feature that I'm not sure I've seen anywhere else. I want to know as quickly as I can what work is most important for me to do so I can serve the community better - and I'd love for GitLight to be a part of that story!

**Comment by colinlienard** [comment]
This will need a lot of thinking in terms of ui but it would be really cool!
