### ISSUE TITLE
Should maximise full on start

### ISSUE THREAD

**Issue by nikitavoloboev** [colinlienard/gitlight#76]
<img width="944" alt="image" src="https://github.com/colinlienard/gitlight/assets/6391776/119311bb-b8c1-4094-a6e8-78aa34a56a86">

When starting the app I see above. I'd love if it was maximised.

**Comment by colinlienard** [comment]
I think to best way to adress your problem would be to store the window state after closing it, which can apparently be achieved with this plugin: https://github.com/tauri-apps/tauri-plugin-window-state

Might do it this weekend
